version: "3"

services:
  argus:
    container_name: argus
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - influxdb2
      - rabbitmq
    ports:
      - 5000:5000
    volumes:
      - ./src:/app
    
  celery-worker:
    build:
      context: .
    command: celery -A app.celery_app worker --loglevel=info -E
    depends_on:
      - rabbitmq
      - argus
    environment:
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672//
    volumes:
      - ./src:/app

  celery-beat:
    build:
      context: .
    command: celery -A app.celery_app beat --loglevel=info
    depends_on:
      - rabbitmq
      - argus
    environment:
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672//
    volumes:
      - ./src:/app
      
  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - 8086:8086

    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


volumes:
  influxdb2-data:
  influxdb2-config:
  rabbitmq_data:
